### ISSUE TITLE
ModuleNotFoundError: No module named 'cgi'

### ISSUE THREAD

**Issue by Nazat9** [rpetit3/fastq-dl#34]
Hi! I installed the environment as mentioned and without specifying a python version. When I ran the next command:
`fastq-dl --accession XXXXX --provider XXX`

I got the error:

> File "/home/../../envs/fastq-dl/lib/python3.13/site-packages/requests_ftp/ftp.py", line 9, in <module>
> ModuleNotFoundError: No module named 'cgi'

Indeed this module is imported in the script ftp.py

Reading a bit, the module cgi was deprecated since python version 3.11 and removed in 3.13. My python version in that moment was 3.13.
#https://github.com/cherrypy/cherrypy/issues/2014
#https://docs.python.org/3.12/library/cgi.html

My solution was to install in the environment python version 3.9 and it worked nicely. 

`conda install python=3.9`

**Comment by mortunco** [comment]
This also fixes the problem.

https://stackoverflow.com/questions/78635741/drop-in-replacement-for-the-cgi-module

`pip install legacy-cgi`


```
$ fastq-dl --version
...
...
...
ModuleNotFoundError: No module named 'cgi'
$ pip install legacy-cgi
Collecting legacy-cgi
  Downloading legacy_cgi-2.6.2-py3-none-any.whl.metadata (1.9 kB)
Downloading legacy_cgi-2.6.2-py3-none-any.whl (19 kB)
Installing collected packages: legacy-cgi
Successfully installed legacy-cgi-2.6.2
(single_big_env) [ec2-user@ip-172-31-74-174 sc-ftdb]$ fastq-dl --version
fastq-dl, version 2.0.4
```

**Comment by mrsajadpp** [comment]
now getting 
```
PS C:\Sajad\verifeye> & C:/Users/mrsaj/AppData/Local/Microsoft/WindowsApps/python3.13.exe c:/Sajad/verifeye/app.py
Traceback (most recent call last):
  File "c:\Sajad\verifeye\app.py", line 16, in <module>
    from groq import Groq
  File "C:\Users\mrsaj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\groq\__init__.py", line 3, in <module>
    from . import types
  File "C:\Users\mrsaj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\groq\types\__init__.py", line 5, in <module>
    from .model import Model as Model
  File "C:\Users\mrsaj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\groq\types\model.py", line 5, in <module>
    from .._models import BaseModel
  File "C:\Users\mrsaj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\groq\_models.py", line 25, in <module>
    from ._types import (
    ...<9 lines>...
    )
  File "C:\Users\mrsaj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\groq\_types.py", line 23, in <module>
    from httpx import URL, Proxy, Timeout, Response, BaseTransport, AsyncBaseTransport
ImportError: cannot import name 'BaseTransport' from 'httpx' (C:\Users\mrsaj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\httpx\__init__.py). Did you mean: 'ASGITransport'?
PS C:\Sajad\verifeye> 
```

**Comment by rpetit3** [comment]
Hello everyone,

I've released a new version that pins Python to <3.13. I will add compatibility with 3.13 in a future release.

Cheers,
Robert

**Comment by alexhermida** [comment]
👋🏽  Hello, just found this issue open, additionally in case you strongly need at least Python 3.13 you can use [legacy-cgi](https://github.com/jackrosenthal/legacy-cgi)

Cheers
